name: Update Docker Hub Description
on:
  push:
    branches:
      - main  
    paths:
    - '*.md'
    - .github/workflows/dockerhub-description.yml
  workflow_dispatch: {}
jobs:
  lint_and_update:
    name: Lint and Update Description
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v3.3.0
      with:
        files: .
    - name: Update Description on Docker Hub
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: danielptv/postgres-multiple-databases
        short-description: ${{ github.event.repository.description }}
        enable-url-completion: true
